### ISSUE TITLE
Display uploaded size of VHD

### ISSUE THREAD

**Issue by colemickens** [Microsoft/azure-vhd-utils-for-go#12]
(This a very minor possible suggestion.)

I've created a 30GB VHD. Based on the estimated upload duration, I feel safe that it's not uploading all 30GB, and from guessing at `Empty ranges: 14838/15360`.

Suggestion is to change the output from this:
```
2016/03/09 16:29:14 Using default container 'vhds'
2016/03/09 16:29:14 Using default parallelism [8*NumCPU] : 32
Computing MD5 Checksum..
 Completed:  99% RemainingTime: 00h:00m:00s Throughput: 3827 MB/sec
Detecting empty ranges..
 Empty ranges : 14838/15360
Uploading the VHD..
 Completed:  22% RemainingTime: 00h:12m:23s Throughput: 8 MB/sec   | 
```

to include information about "effective upload size" after it "Detects empty ranges..", or having a line  "Uploaded X MB, Remaining X MB" along with the throughput. That way I can be immediately sure that I'm only uploading non-zero bytes. Something like:

```
2016/03/09 16:29:14 Using default container 'vhds'
2016/03/09 16:29:14 Using default parallelism [8*NumCPU] : 32
Computing MD5 Checksum..
 Completed:  99% RemainingTime: 00h:00m:00s Throughput: 3827 MB/sec
Detecting empty ranges..
 Empty ranges : 14838/15360
 Effective upload size: 1044 MB (from 30720 MB originally)
Uploading the VHD..
 Completed:  22% (229.68 MB) - RemainingTime: 00h:12m:23s (814.32MB) - Throughput: 8 MB/sec   | 
```

This tool is very useful, by the way. Much better throughput than I've had with the xplat-cli also, not to mention being able to upload large VHDs without using up all of my bandwidth.

**Comment by anuchandy** [comment]
Showing uploaded size is a nice addition, will add that.

**Comment by anuchandy** [comment]
Closing this, now we show effective upload size and uploaded bytes.
