### ISSUE TITLE
vhdUploadCmdHandler.go:238: not enough arguments in call to client.SetBlobMetadata

### ISSUE THREAD

**Issue by mcronce** [Microsoft/azure-vhd-utils-for-go#20]
It looks like https://github.com/Azure/azure-sdk-for-go/ made a change to the function signature for BlobStorageClient.SetBlobMetadata() /blob/master/storage/blob.go, which adds a fourth parameter.

I'm about to fork the repo and submit a pull request, just wanted to document it first.

**Comment by anuchandy** [comment]
@mcronce thanks for the contribution!

**Comment by tomck** [comment]
Seems there may be an inverse now...

```
go get github.com/Microsoft/azure-vhd-utils-for-go
# github.com/Microsoft/azure-vhd-utils-for-go
../gowork/src/github.com/Microsoft/azure-vhd-utils-for-go/vhdUploadCmdHandler.go:242: too many arguments in call to client.SetBlobMetadata
```
