### ISSUE TITLE
'DEPRECATED Action signature' warning

### ISSUE THREAD

**Issue by nathanleclaire** [Microsoft/azure-vhd-utils-for-go#25]
@anuchandy Thanks so much for this program.

I am running it after installing with `go get` and I get a warning on most command invocations:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

FYI.  Probably want to do a `go get -u` and check that out.

**Comment by anuchandy** [comment]
@nathanleclaire  - looks like the cli we depend on got updated, the cli action signature requires "error" as return type instead of "void", will fix it. Refernece: https://github.com/urfave/cli/issues/370

is it blocking you from uploading vhd?

**Comment by nathanleclaire** [comment]
> is it blocking you from uploading vhd?

No the upload seems to go fine, it's just a warning.  Thanks!
